### ISSUE TITLE
Better index for point GeoJSON atlas makes (versus page grids)

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#117]
The usual method is to draw a grid of page rectangles onto the map to make an atlas and the index page reflects that arrangement.

When a user uploads data from Ushahidi or other GeoJSON formatted data, the index is skipped because it's one page per feature. The feature can be close together or far apart geographically, but they always get their own page.

A future release would show the distribution of the points on the index page. Ideally they'd be numbered and keyed to an lookup table printed in text on a 2nd (etc) sheet (ii, iii, iv, etc).

**Comment by sethfitz** [comment]
This applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
