### ISSUE TITLE
carry thru atlas title + freeform text + custom map tiles in Make process templates

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#151]
Using:
http://fieldpapers.org/make-canned-atlas-template.html

If I enter in a title (atlas_title ) and text (atlas_text), those are not carrie thru to:

http://fieldpapers.org/make-step3-info.php

If I enter in a custom map tiles provider, that isn't carried thru to:

(like: http://tile.stamen.com/toner-lite/{Z}/{X}/{Y}.png)

http://fieldpapers.org/make-step2-geography.php?zoom=15&lat=37.8045&lon=-122.2712

**Comment by sethfitz** [comment]
This applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).

**Comment by sethfitz** [comment]
See also https://github.com/fieldpapers/fieldpapers/issues/116
