### ISSUE TITLE
Add custom image area to Atlas template

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#153]
Aka: header PDF stamp.

This is important for allowing organizations to "brand" the atlases made by themselves. Helps spread the Field Papers brand by allowing the org to spread their own brand, increase "I want that" within and between orgs working in the same area. From KC.

**Comment by sethfitz** [comment]
This applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
