### ISSUE TITLE
'include geolocation barcode' option

### ISSUE THREAD

**Issue by harry-wood** [stamen/fieldpapers#159]
If you just want a nice map print-out, then the barcode and other bits for geolocating a scan, are clutter.

A new option 'include geolocation barcode' would be ticked by default, but not including those bits would be useful.

Of course that explicitly turns this into a merely an awesome interface for map printouts, which is probably frustrating having implemented the very clever geolocating scan tricks!

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
