### ISSUE TITLE
Fix Zoom UI on Atlas view for large atlases

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#161]
Seems like the zoom b0rks when there are lots of pages in an atlas...

http://fieldpapers.org/atlas.php?id=b7hrd4mg

Doesn't zoom into the selected page correctly?

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
