### ISSUE TITLE
Geotiff produced by Walking papers fails to load in ImportImagePlugin in JOSM

### ISSUE THREAD

**Issue by M4rtinK** [stamen/fieldpapers#165]
The [ImageImportPlugin](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/ImportImagePlugin) in JOSM fails to load the geotiffs created by Fieldpapers.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
