### ISSUE TITLE
Add option for Contour Line overlay

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#166]
On Jan 21, 2013, at 6:22 AM, Krischan Makowka wrote:

Hello Stamen team

First of thanks for making such a great tool for field OSM mappers!

However is it possible somehow to display contour lines similar to those found on OpenCycleMap in Field Papers, preferably in the black and white view?

Thanks a lot!

-Krischan

**Comment by sethfitz** [comment]
OpenCycleMap is now in the dropdown list.
