### ISSUE TITLE
Better handling of WalkingPapers.org snapshot editing

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#168]
Example:
http://fieldpapers.org/snapshot.php?id=pmhgr598

Right now FieldPapers.org will read in a snapshot and allow editing on it.

But the page count, Finished button, Atlas name link etc are all busted. They should be special cased for this.

**Comment by sethfitz** [comment]
https://github.com/fieldpapers/fieldpapers/issues/111
