### ISSUE TITLE
Allow other paper sizes

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#170]
Right now it's just letter sized ANSII? 

Should also allow for European sizes (A4 specifically, A3 less so).

Occasionally a large poster size for plotter printing would be useful.

**Comment by brendancol** [comment]
Hey was this ever completed?

**Comment by almccon** [comment]
It's one of the top TODOs that we will get to work on in an impeding phase of work. So it should be coming soon!

**Comment by brendancol** [comment]
Awesome! I've seen references to paper_size in compose.py:

`paper_size = {'letter': 'ltr', 'a4': 'a4', 'a3': 'a3'}[paper_size.lower()]`

**Comment by brendancol** [comment]
seems like all that is needed is a little UI love on make-step-3.  

Can I go ahead and change the paper_size input from "hidden" to a dropdownlist? Any reason to wait on that?

**Comment by mojodna** [comment]
Nah, go for it.  That's embarrassing if that's all that it took--this has been a desire for quite a while.  I have to admit that the parts of the printing code that actually create the PDF remain a black box to me.

**Comment by sethfitz** [comment]
Added during the relaunch.
