### ISSUE TITLE
Consider wufoo forms for data

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#182]
http://www.wufoo.com

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
