### ISSUE TITLE
Parse OSM-style permalinks

### ISSUE THREAD

**Issue by mojodna** [stamen/fieldpapers#183]
...to ease copying and pasting locations from OSM/OpenLayers-powered sites.

E.g.
http://www.openstreetmap.org/?zoom=12&lat=47.47661&lon=19.09595&layers=B00000

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
