### ISSUE TITLE
Load OSM POIs on-demand and render them as a separate layer.

### ISSUE THREAD

**Issue by mojodna** [stamen/fieldpapers#184]
Use [Overpass](http://wiki.openstreetmap.org/wiki/Overpass_API) to load POIs on demand and render them atop styles like Toner (with minimal labels).

That way we can get the speed benefits from pre-rendered (if aged) tiles with up-to-date landmarks.  Not great for annotating geometries (since the basemap would be out of date), but potentially highly useful for adding addresses and amenities and/or displaying up-to-date landmarks.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
