### ISSUE TITLE
Determine next step for geocoding

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#188]
The new BOSS Geocoder is "free" for less than 2000 requests a day. http://developer.yahoo.com/boss/geo/

However, use is thru YQL tables. 

If we ever had higher usage, we need to make allowances for that and going pro. This is done by setting an oAuth app id.

Use this PHP library:
https://github.com/yahoo/yos-social-php5

Code example:
http://developer.yahoo.com/yql/guide/yql-code-examples.html#yql_php

General reading (circular, warning!):
http://developer.yahoo.com/boss/geo/docs/upgrade.html

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
