### ISSUE TITLE
Custom TMS layers busted

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#193]
As described on the about page:
http://fieldpapers.org/about.php

Custom Map Styles - TMS endpoints - Already published your basemap online as a tiled map service? Use our template tool detailed above to point to the TMS endpoint. Example: http://tile.stamen.com/watercolor/{Z}/{X}/{Y}.jpg.

Does not generate atlases with that custom endpoint. Defaults to Toner instead.

**Comment by jeffhaack** [comment]
Indeed, seems broken

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
