### ISSUE TITLE
Zoom buttons should grey out when they're inactive

### ISSUE THREAD

**Issue by ericrodenbeck** [stamen/fieldpapers#195]
Looks like you can only zoom in to about 12? 

http://fieldpapers.org/make-step2-geography.php?zoom=12&lat=51.71814&lon=8.75204

There may be something else going on, the URL doesn't seem to change when I move the map around.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
