### ISSUE TITLE
ensure snapshots are associated with atlases

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#199]
Reports on the internet say:

"Appears that they aren't being registered to an atlas - they all come in as "Page None of untitled atlas". Notes on the pages get saved, but can't be exported since they aren't a part of a defined atlas."

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
