### ISSUE TITLE
Need templates for error/status pages, not just a php view

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#2]
Anywhere we need to show some sort of status/error/progress, you should see that within the FP nav/footer. E.g. verify.php should take you to a Field Papers page. 

Ideally, error messages would be integrated into the page it refers to. E.g., if your passwords don't match when you create an account, the error should show on the login screen itself.

**Comment by sethfitz** [comment]
This applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
