### ISSUE TITLE
Messaging when foreign atlases are scanned

### ISSUE THREAD

**Issue by mojodna** [stamen/fieldpapers#202]
Field Papers and Walking Papers are compatible, but scanning a WP print results in confusing verbiage: "Add notes to page None of 0 from Untitled" (where Untitled links to an atlas w/ an id of `None`).  Foreign atlases should continue to be supported, but we should display a message to that effect.

E.g. http://fieldpapers.org/snapshot.php?id=ln64mm7d

**Comment by sethfitz** [comment]
https://github.com/fieldpapers/fieldpapers/issues/111
