### ISSUE TITLE
Work out why 3rd layout option isn't available

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#203]
See line 50 here:
https://github.com/stamen/fieldpapers/blob/master/site/templates/make-step4-layout.html.tpl

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
