### ISSUE TITLE
Make nice_relativetime show more than days

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#205]
Like, weeks, months, years...

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
