### ISSUE TITLE
Reject prints with too many pages

### ISSUE THREAD

**Issue by mojodna** [stamen/fieldpapers#206]
While clearing out the queue, I found a 1000 page atlas that had repeatedly failed to be composed...

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
