### ISSUE TITLE
Reject (or address?) prints with problematic aspect ratios

### ISSUE THREAD

**Issue by mojodna** [stamen/fieldpapers#207]
Exceedingly tall or wide prints (e.g. [16.115227008425, 48.084447998399, 16.648063904572, 54.934862380261) fail when creating the index page (after sitting for a significant amount of time).  This is either due to the number of tiles necessary to maintain the same aspect ratio on a printed page or due to the target dimensions.

This happens with both ModestMaps-py and stitch.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
