### ISSUE TITLE
Pass image size into atlases.php

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#210]
Thanks to the nice new "pinmaps" style layout, when the page loads, it skips around a bit until all the images have loaded in.

Wondering if it's possible to pass the image sizes into the page to avoid that skipping around you see?

http://georgepapers.local/atlases.php

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
