### ISSUE TITLE
Snapshot can be dragged when digitizing polygons

### ISSUE THREAD

**Issue by ghost** [stamen/fieldpapers#220]
When digitizing a polygon, if a user clicks their mouse and does not release, the snapshot can be repositioned. This causes the polygon's position to shift and annoyance level to increase.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
