### ISSUE TITLE
Atlas PDF download has blacked out data

### ISSUE THREAD

**Issue by irfus** [stamen/fieldpapers#221]
I created an atlas using Satellite+Labels as the base (here, http://fieldpapers.org/atlas.php?id=8537ttxx). The pdf download has most pages showing either a black space or the imagery with black artifacts on it.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
