### ISSUE TITLE
Zoom not being set in print table

### ISSUE THREAD

**Issue by miketahani** [stamen/fieldpapers#222]
All zooms are NULL

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
