### ISSUE TITLE
Add note per atlas to connect to atlases copied or refreshed *from* the one you're looking at?

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#225]
Sean! I saw your awesome note in the atlas history connecting to "source" atlases that were either copied or refreshed from...

![image](https://f.cloud.github.com/assets/354542/678030/c860a82e-d929-11e2-8c6f-3fe5c1a42f29.png)

Is it possible to add a note the other direction too? Linking to the Child atlas from the Parent?

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
