### ISSUE TITLE
Improve First View experience of Make UI?

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#226]
Andrew Wiseman on June 6, 2013 at 7:44 am said:
One thing a couple of non-techies were confused about was the first part where you select your area for a — they were having a hard time figuring out how to resize it and move it and stuff. Would it be possible to have some kind of little pop-up that has arrows and says “Click and drag here to resize, click here to move, click here to add or remove pages, click here for different backgrounds” or something?

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
