### ISSUE TITLE
Display scale in kilometers and miles?

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#229]
Andrew Wiseman on June 7, 2013 at 11:07 am said:
Can the scale be in both miles and kilometers? Right now, it is just in kilometers on the PDF. (This, to me, is pretty low priority)

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
