### ISSUE TITLE
Add $title info to Snapshots.php

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#232]
E.g. http://fieldpapers.local/snapshots.php?place=2347565

![image](https://f.cloud.github.com/assets/354542/696898/1e92428a-dcf3-11e2-84d3-415a18fb978e.png)

Ideally, that h2.header bar reads:

Atlases | 23 Snapshots

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
