### ISSUE TITLE
Question/Nice to Have - have atlases cascade from top to bottom newest first

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#246]
Right now, in the pinterest layout, it looks like the left column is newest, then mid, then right.

No idea what's involved in making it so it's newest from top left across instead of down... any thoughts?

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
