### ISSUE TITLE
Zooming in to an atlas page bumps the copy/download buttons

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#247]
![image](https://f.cloud.github.com/assets/354542/706493/5fb70b18-ddef-11e2-9605-8e2078a19658.png)

http://fieldpapers.local/atlas.php?id=tqzhn9c6#13/30.0349/31.3279

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
