### ISSUE TITLE
Search snapshot by location

### ISSUE THREAD

**Issue by maning** [stamen/fieldpapers#249]
Similar to making an atlas, the first step is type an initial location.  It would be nice to allow searching snapshots by location.  For the mean time I had to manually look to the older snapshots to check my previously uploaded scans.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
