### ISSUE TITLE
Please add singular for atlas & snapshot count

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#250]
http://fieldpapers.org/atlases.php?place=90009887

![image](https://f.cloud.github.com/assets/354542/712311/7cd2a042-dea6-11e2-8b4a-2a68f299c4e6.png)

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
