### ISSUE TITLE
MBTiles uploader returns a blank page

### ISSUE THREAD

**Issue by maning** [stamen/fieldpapers#255]
I tried to upload small (1.8 MB) MBTiles file using the [uploader tool](http://fieldpapers.org/upload_mbtiles.php).  After several minutes, I get a completely blank page.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
