### ISSUE TITLE
Uploaded snapshots does not appear in the recent snapshot page and the atlas page.

### ISSUE THREAD

**Issue by maning** [stamen/fieldpapers#256]
I uploaded a scan from this atlas: http://fieldpapers.org/atlas.php?id=tb23676v#16/14.6574/121.1098

The scan was properly processed: http://fieldpapers.org/snapshot.php?id=llk796ms#16/14.6602/121.1126

But it doesn't appear in the recent activity of the atlas nor the main recent snapshots: http://fieldpapers.org/snapshots.php

**Comment by mccarthyryanc** [comment]
I am having this issue, but for a private atlas.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
