### ISSUE TITLE
Add new JOSM RC Edit Link

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#257]
From here: https://github.com/stamen/fieldpapers/issues/156#issuecomment-20175398

Says maning:
Related to JOSM, I think a good solution is to use the remotecontrol plugin [0].  The JOSM RC plugin can load the bbox of the atlas/scan and at the same time, add a custom baselayer like a TMS/WMS.  This is what is used in the HOT Tasking Manager. Example is the task for Ambon [1].  Which loads a custom imagery tile from NextView.

The JOSM RC URL looks like this 
```
http://127.0.0.1:8111/imagery?title=[New%20Imagery%20Update]%20Help%20Map%20Ambon%20after%20the%20floods&type=htt&url=http://hiu-maps.net/hot/1.0.0/ambon_flipped/{zoom}/{x}/{y}.png
```
Currently, no image was loaded perhaps the imagery is not available anymore, but I think you get the idea. :)

[0] http://wiki.openstreetmap.org/wiki/JOSM/Plugins/RemoteControl
[1] http://tasks.hotosm.org/job/45

**Comment by sethfitz** [comment]
https://github.com/fieldpapers/fieldpapers/issues/96
