### ISSUE TITLE
Imagery Not Working

### ISSUE THREAD

**Issue by jeffhaack** [stamen/fieldpapers#258]
Hey guys,

I wonder if anyone can take a quick look at the site - the Bing imagery does not seem to be appearing on the papers, for a couple days now.

Cheers,
Jeff

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
