### ISSUE TITLE
Zoom level of Overview Map on print.php should be relative to the map zoom level, not a fixed number

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#26]
GLO:

See:
http://fieldpapers.org/print.php?id=2l23wzsz

The atlas area is the USA. The overview shows me the American south.

**Comment by sethfitz** [comment]
This applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
