### ISSUE TITLE
Use lower resolution for OSM imagery

### ISSUE THREAD

**Issue by pbb72** [stamen/fieldpapers#260]
The resolution of the maps is currently so low, that thin lines like paths and footways become mangled by the JPEG compression used in the PDF files. Especially red footways on green forests or grassfields become horrible.

Also, these lines become too thin to be printed out by less capable printers.

The way I see it, the resolution could easily be halved or even quartered.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
