### ISSUE TITLE
Scans from Atlas 23vbtt7v Are Not Working

### ISSUE THREAD

**Issue by wonderchook** [stamen/fieldpapers#262]
Every picture we have uploaded from this Atlas is failing: http://fieldpapers.org/atlas.php?id=23vbtt7v#15/20.8334/106.6971

I'm not sure what the issue might be, we've done the same process I always do with FieldPapers. 

Note: I've tried a few different cameras and uploading directly from Mobile Phones and a Computer (in the past sometimes network problems were an issue, but I don't believe this is the case)

![20131008_083301](https://f.cloud.github.com/assets/67992/1286459/6eb1992c-2fd3-11e3-83fa-d7a9567d54e9.jpg)
![20131005_161654](https://f.cloud.github.com/assets/67992/1286461/88c58d14-2fd3-11e3-9b7c-18b6b505d73d.jpg)

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
