### ISSUE TITLE
Redirect to iD on openstreetmap.org, not openstreetmap.us 

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#265]
Now that iD is the default editor on the main page...

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
