### ISSUE TITLE
Capacity for multilanguage interface?

### ISSUE THREAD

**Issue by severinmenard** [stamen/fieldpapers#267]
Would like to know if the website is ready to add translations of the interface. Would like to create it in French. Would work on this before the end of the month as part of a OSM tools translation run.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
