### ISSUE TITLE
No interface for deleting atlases or snapshots

### ISSUE THREAD

**Issue by kaldari** [stamen/fieldpapers#269]
I wasn't able to find any interface for deleting atlases or snapshots after they had been created.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
