### ISSUE TITLE
QR Code and legend are hiding parts of the atlas

### ISSUE THREAD

**Issue by mh166** [stamen/fieldpapers#270]
The QR Code in the lower right corner of each page of an atlas hides away the map data that lies behind. Unfortunately this is not compensated in any way.

I'd suggest to stuff the QR Code somewhere above the actual map to keep the view of the map free of it.

Same goes to the legend. Although this time it is not necessary to keep it machine readable. So maybe it would be sufficent to add some transparency to it, I guess.

Regards,
mh166

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
