### ISSUE TITLE
Prevent black or white atlases.

### ISSUE THREAD

**Issue by mcdlee** [stamen/fieldpapers#271]
I got some black or white atlases, like this: http://fieldpapers.org/files/prints/492w432n/field-paper-492w432n.pdf
Maybe it is related to low resolution or low quality of Bing Aerial Imagery.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
