### ISSUE TITLE
Problem with uploading fieldpapers

### ISSUE THREAD

**Issue by Cobe2487** [stamen/fieldpapers#272]
I have a big problem with uploading my fieldpapers on fieldpapers.org. I tried several times to upload my scanned papers, always with the same result:  
“Giving up. You might try uploading your scan again, making sure that it’s at a reasonably high resolution (200+ dpi for a full sheet of paper is normal) and right-side up. A legible QR code is critical.”
I tried it with different dpis (300 and 600), different formats like jpg, png, tiff. Now I run out of ideas what the problem could be and how to solve it…
Somebody has any ideas what the problem with my papers or pc or whatever could be?

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
