### ISSUE TITLE
http://fieldpapers.org doesn't support TLS

### ISSUE THREAD

**Issue by mattcen** [stamen/fieldpapers#274]
I noticed tonight that http://fieldpapers.org doesn't support TLS, and therefore passwords are sent in plaintext. This doesn't bother me because I use different passwords everywhere, but the vast majority of the community are likely to share passwords between sites, making this more of an issue.

Any possibility that TLS support can be added to the website, even if just for auth?

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
