### ISSUE TITLE
uploading: "Sorry, expiration date " Tue, 05 Aug 2014 12:03:19 UTC  "has come and gone"

### ISSUE THREAD

**Issue by ImreSamu** [stamen/fieldpapers#285]
When I want upload my image -  i have got this message:
"Sorry, expiration date Tue, 05 Aug 2014 12:03:19 UTC has come and gone - Tue, 05 Aug 2014 05:03:19 -0700"

What is the "expiration date" ?

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
