### ISSUE TITLE
Zoom-out goes to Sudan

### ISSUE THREAD

**Issue by maning** [stamen/fieldpapers#286]
To replicate:
1. Location search: Lilongwe. Next
2. Click zoom out (+)

I've checked in other areas, but it works as expected.  This is a bug only for Lilongwe, Blantyre or other areas in Malawi.

**Comment by almccon** [comment]
Apparently zooming out from Peru sticks you in the Caribbean: https://twitter.com/lxbarth/status/578231120740876288

**Comment by mojodna** [comment]
This has been fixed in the [Rails port](https://github.com/fieldpapers/fp-web) by switching to Leaflet.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
