### ISSUE TITLE
Successfully upload but no snapshot background image?

### ISSUE THREAD

**Issue by it4workflow** [stamen/fieldpapers#287]
Hello,
i successfully uploaded a 11MB 600dpi JPG which results in http://fieldpapers.org/snapshot.php?id=6nbfzpsq without a(ny) background image?
Regards
[Harald Hartmann](https://wiki.openstreetmap.org/wiki/User:Haribo)

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
