### ISSUE TITLE
bad quality after upload of 300dpi jpg

### ISSUE THREAD

**Issue by it4workflow** [stamen/fieldpapers#288]
Hello,
i uploaded a 300dpi JPG which result in http://fieldpapers.org/snapshot.php?id=cwnz6h6m with bad quality in snapshot (iD and JSOM). I also tried an 150dpi version with the same bad quality.
Regards
[Harald Hartmann](https://wiki.openstreetmap.org/wiki/User:Haribo)

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
