### ISSUE TITLE
Bug with Chrome on Windows

### ISSUE THREAD

**Issue by emirhartato** [stamen/fieldpapers#289]
# Problem

When I trying to make a print, under map pages, I can't resize and move the bounding box, when I drag it, the map is panning.

# System

Windows 8.1 64-Bit
Google Chrome Version 36.0.1985.125 m

Thanks in advance

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
