### ISSUE TITLE
"Refresh" doesn't retrieve fresh map tiles

### ISSUE THREAD

**Issue by danstowell** [stamen/fieldpapers#290]
It appears that "Refresh" doesn't flush the fieldpapers cache of map tiles. If I edit OSM to add a building or suchlike, then "Refresh" about 30 minutes later, fieldpapers continues to use the old tiles even after the main OSM website has been showing the new ones for at least 20 minutes.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
