### ISSUE TITLE
"Refresh" does not generate new PDF one-page or half-page

### ISSUE THREAD

**Issue by alexandre-mbm** [stamen/fieldpapers#291]
Examples: [Alexandre](http://fieldpapers.org/atlases.php?user=53f4v6cz)'s atlases "Vila de Ponta Negra". See also the issue #290.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
