### ISSUE TITLE
Notes out of place

### ISSUE THREAD

**Issue by alexandre-mbm** [stamen/fieldpapers#293]
![field-paper-notes-bug](https://cloud.githubusercontent.com/assets/957501/4257575/558c9142-3ac5-11e4-91cf-c3feaaf7dccc.png)

These notes are in different snapshots (and sometimes different pages).

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
