### ISSUE TITLE
Missing a "fit to extent" button to easily make the field papers extent fit to the map extent

### ISSUE THREAD

**Issue by severinmenard** [stamen/fieldpapers#294]
we should have a button to fit the Field Papers window to the map extent. WIthout it, it requires to the FP creator to adjust several times the FP extent everytime he/she zooms in

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
