### ISSUE TITLE
Add better contact links to footer and to atlas generation page

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#295]
So people can let us know if the site gets stuck.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
