### ISSUE TITLE
"Nearby" list is not nearby

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#296]
On this atlas http://fieldpapers.org/atlas.php?id=26rtrwgr#12/49.2535/-123.1042 the list of nearby atlases are in places like South America, Moscow, etc.
![screen shot 2014-11-10 at 3 36 03 pm](https://cloud.githubusercontent.com/assets/1212178/4985895/8624e200-6932-11e4-9472-3f0fe1cd660a.png)

Low priority.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
