### ISSUE TITLE
Using the Red Cross overlay outside of the Philippines results in blank map tiles

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#297]
Here are their tiles: http://a.tiles.mapbox.com/v3/americanredcross.HAIYAN_Atlas_Bounds.html#8/10.855/123.851

So perhaps we are not handling the 404s well?

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
