### ISSUE TITLE
Atlas summary should include overlays, too.

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#298]
It would be useful for debugging if this short summary "9 pages + satellite + labels + landscape + full-page" also included whether the UTM or Red Cross overlay was turned on.

![screen shot 2014-11-10 at 5 33 20 pm](https://cloud.githubusercontent.com/assets/1212178/4986911/d8dd0a8a-6942-11e4-86dd-0b5da4360d58.png)

**Comment by sethfitz** [comment]
https://github.com/fieldpapers/fieldpapers/issues/159
