### ISSUE TITLE
Occasional black tiles, occasional all-black maps

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#299]
Here are combinations I've found that result in all-black maps:

 * Anything + Red Cross overlay (outside of Philippines). See issue #297 
 * Anything using the "satellite + labels" layer [UPDATE: @mojodna fixed this]

**Comment by mojodna** [comment]
Confirmed, this behavior is consistent with a non-responsive tileserver (as is extremely long wait times for retries, which are usually responsible for backing the queue up).

Interestingly, I initially pointed it at the wrong hostname and it failed much more quickly.  Had to wait ~5+ min to produce a failure like this (after killing a proxy after a few successful requests):

![image](https://cloud.githubusercontent.com/assets/45/6424155/f49a6d48-bea7-11e4-8d05-d8591d78ce3c.png)

404s are retried multiple times at increasingly lower zoom levels (going deep into negative territory), which can result in an excessive number of requests (for tile overlays too) and corresponding time. The eventual result is a fully black map.  This could explain the pixelated Red Cross overlay, especially if that's on the northern boundary of the available tiles.

I'm not sure yet what leads to overlays on black tiles.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
