### ISSUE TITLE
"copy this atlas" should allow changes in providers

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#305]
When I click "copy this atlas" I might want to use a different basemap provider, but keep the same extent.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
