### ISSUE TITLE
Show page number on each atlas PDF page, A1, A2, B1, etc

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#306]
Currently the PDF pages are unnumbered. It is up to the user to figure out how the atlas pages fit together. 

See: https://lists.openstreetmap.org/pipermail/talk/2014-November/071515.html

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
