### ISSUE TITLE
Improve resolution and/or zoom for scans

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#319]
The tiles generated from some scans are so pixelated they are unusable. This happens even when the source GeoTIFF is fine. For example this one: http://fieldpapers.org/snapshot.php?id=fx25xvmw#18/4.53560/-75.66991 You can't even read the writing on it. But the GeoTIFF is fine: http://fieldpapers.org/files/scans/fx25xvmw/walking-paper-fx25xvmw.tif

I also note that the tiles stop at zoom 18. For this particular scan, zoom 18 is insufficient. Could we go to zoom 19 or 20?

Looks like others have similar problems with image quality of the tiles: see #288

**Comment by humano** [comment]
I also have this problem http://fieldpapers.org/snapshot.php?id=kkr27tv7#18/4.53619/-75.66834

**Comment by mojodna** [comment]
Not a now solution, but I'm thinking that since we're working with GeoTIFF sources (produced by the decoder), we can take a page from the terrain project and render tiles on-demand (and whatever zooms are desired) rather than pre-rendering everything.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
