### ISSUE TITLE
Allow direct upload through a Field Papers app

### ISSUE THREAD

**Issue by DaCor1** [stamen/fieldpapers#324]
Field papers works fantastically, however there is a disjointed moment after you've completed a survey and want to use the sheets in JOSM or iD. 

The upload process seems like it is ripe for doing through an app. How this would work would be simple. Login to field papers through the app, app will bring you straight to your gallery, select your image to upload, upload. 

Doing this presently through a browser on the phone is tedious.

**Comment by mojodna** [comment]
I like it.  That points to the need for a more extensive API, allowing 3rd-party applications to interact with FP.

We're revisiting the front-end here and may soon be in a position where a basic implementation is feasible: http://github.com/fieldpapers/fp-web

**Comment by sethfitz** [comment]
https://github.com/fieldpapers/fieldpapers/issues/162
