### ISSUE TITLE
Zooms should be clamped to availability (z20 tiles are requested despite not being available)

### ISSUE THREAD

**Issue by DaCor1** [stamen/fieldpapers#325]
No error is given, atlas is created normally, imagery shows up on first page, but not on subsequent pages. Example below. 

http://fieldpapers.org/atlas.php?id=fxmt9x5r#18/-29.82334/27.24041

**Comment by mojodna** [comment]
There have been no changes, so this is either a transient error (my guess) or a long-time problem with half-page prints.

**Comment by DaCor1** [comment]
Ah, I didn't try full page prints so that may resolve it, the only thing is
the half page maps are better when you have a large atlas pack

**Comment by mojodna** [comment]
Agreed.  Can you try full-page prints as well as recreating that atlas?  That'll help me narrow down the problem.

**Comment by DaCor1** [comment]
Sure, will post later with a result

**Comment by mojodna** [comment]
The index page is using imagery from z19 (available), subsequent pages from z20 (not available), which is rendering white JPEGs.

http://tile.stamen.com/bing-lite/20/167536/405316.jpg

**Comment by aawiseman** [comment]
Interesting. I could reach out to the Mapbox folks unless you all already have a good contact? I know a few of them, I bet they'd want to help.

**Comment by mojodna** [comment]
You'll get to it first, so go for it!  Thanks!

**Comment by aawiseman** [comment]
Will do! I should note I am in no ways a coder though, so I may to defer to you all once I hear back.

**Comment by aawiseman** [comment]
Right, they confirmed they just don't have imagery that far in. It's a little confusing though since it looks ok when you choose your extent, but then if you zoom in one layer farther the imagery goes away.

They (Ian Villeda) suggested using "overzoom": "You can overzoom imagery tho, letting you still see imagery for zoom levels at which it does not exist https://www.mapbox.com/mapbox.js/example/v1.0.0/overzoom/ but the field paper folks would have to implement this " 

Another option might be including some kind of message, "if you get black boxes with x's, try zooming farther out."

**Comment by mojodna** [comment]
We're effectively overzooming by scaling images.  I just added support for this to the Rails port.

**Comment by aawiseman** [comment]
I just tried it again (http://fieldpapers.org/files/prints/q9nvs757/field-paper-q9nvs757.pdf) and am still getting the black squares. Does it only overzoom to a certain level?

**Comment by mojodna** [comment]
fieldpapers.org doesn't know what zoom levels are available, so it's possible that it's requesting tiles for zoom 23, which aren't going to exist.  The Rails port clamps 0-19 (for Mapbox Satellite) to avoid the black boxes with Xs.

For now, your best bet is to generate another atlas with a zoomed out view if you see all black squares.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
