### ISSUE TITLE
Upload doesn't work

### ISSUE THREAD

**Issue by malenki** [stamen/fieldpapers#326]
I have two scans I tried to upload but the server side gave up. I scanned the images as TIF with 300 DPI 3500x2500 (20 MB) and converted that to JPG of the same pixelsize (1,7 MB). None of it the server wanted. What's the problem?
[Here](http://malenki.ch/d/files.zip) are the files.

PS: Tried with 
Chromium Version 40.0.2214.91 Built on 8.0, running on Debian 8.0 (64-bit)
FF 31.4.0

**Comment by kempj2** [comment]
I have been playing around with this pretty extensively today and have also run into a problem with the upload. It has been working fine when the atlas is not set to private. When the atlas is set to private the upload goes through the motions and seems to work but the snapshot never shows up in the atlas itself. Doe this sound similar to your issue?

**Comment by malenki** [comment]
I have no account, just wanted to upload two scans more or less anonymously. I created the papers last week and used the default presets. My first try on this.

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
