### ISSUE TITLE
Mapbox Satellite showing as black tiles with X-es

### ISSUE THREAD

**Issue by almccon** [stamen/fieldpapers#327]
Not sure if this is related to #325... unlike that issue, the maps are black, not white. And it's happening for full-page altases as well.

Here's one in Senegal that is failing: http://fieldpapers.org/files/prints/2w23wv3n/field-paper-2w23wv3n.pdf and another in SF: http://fieldpapers.org/files/prints/hhd3lldr/field-paper-hhd3lldr.pdf

Reported by @aawiseman via email

![screen shot 2015-02-27 at 2 09 52 pm](https://cloud.githubusercontent.com/assets/1212178/6422163/55e91ba8-be8a-11e4-88aa-3bf69d050eff.png)

**Comment by mojodna** [comment]
They're not fully black--the roads are visible.  What seems to be happening here is that Mapbox is failing to composite satellite imagery at zoom 20 (that would potentially explain the Xs):

http://api.tiles.mapbox.com/v3/stamen.i808gmk6.html#20/37.77313/-122.48351

**Comment by mojodna** [comment]
Yup, duplicates #325.
