### ISSUE TITLE
Fail message: Missing... Something.

### ISSUE THREAD

**Issue by pedrito1414** [stamen/fieldpapers#328]
Hi, I am trying to make an atlas and the process is fine until I hit finish. 

Then I get a blank screen with just 'Missing... Something.' written in the top left (image attached)
![fieldpapers error](https://cloud.githubusercontent.com/assets/8447248/6945044/f794632c-d88e-11e4-88fd-49c801c197c0.png)

**Comment by pedrito1414** [comment]
Strange. I can get it to create an atlas with only two pages. I want a 64 (8x8) pager. I have also tried 16 (4x4), but still get the error.

**Comment by almccon** [comment]
Strange. I was able to create an 8x8 successfully: http://fieldpapers.org/atlas.php?id=92t6qknn#15/37.7947/-122.4638 But perhaps it has something to do with the other parameters you included? Or something else about the overall size?

I'm sorry I have no idea what's going on with your error. :(

Within a week or two we can test the same parameters on the new site (under development here: https://github.com/fieldpapers), but it's not quite ready yet to test that.

**Comment by pedrito1414** [comment]
No worries. I have made a set of four atlases to cover the area. Good luck with testing the new version!

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
