### ISSUE TITLE
Can't upload map

### ISSUE THREAD

**Issue by mneuman** [stamen/fieldpapers#330]
![fullsizerender](https://cloud.githubusercontent.com/assets/9874392/7620209/248029de-f973-11e4-8f32-24c43fe9944e.jpg)

This won't work - strange...

**Comment by mojodna** [comment]
Were you uploading to fieldpapers.org or next.fieldpapers.org?  If the latter, it may be related to the face that it was generated for fieldpapers.org and they're not yet entirely portable between systems.

**Comment by mneuman** [comment]
I tried both. Will do some
More testing later. 

.m

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).
