### ISSUE TITLE
The generated pdf map is not sharp

### ISSUE THREAD

**Issue by psvenz** [stamen/fieldpapers#331]
I just tried the new fieldpapers and generated this map:

https://s3.amazonaws.com/files.fieldpapers.org/atlases/5ir52z7j/atlas-5ir52z7j.pdf

However, i find the text and details in the image a little bit too compressed. A lot of artifacts is seems to be visible around text and other details. Would it be possible to adjust compression settings in pdf generation? 
![fieldpapers](https://cloud.githubusercontent.com/assets/4777731/8000135/fe3df2ce-0b56-11e5-8536-04e0ea0f8478.png)

**Comment by sethfitz** [comment]
[Field Papers](http://fieldpapers.org/) was relaunched in May 2015 and moved to the [Field Papers organization](https://github.com/fieldpapers).

This issue applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).

**Comment by psvenz** [comment]
Thanks for clarifying.
