### ISSUE TITLE
Add support for paper sizes up to A0

### ISSUE THREAD

**Issue by bgirardot** [stamen/fieldpapers#334]
We have a use case that I do not think is all that uncommon our might not be all that uncommon if it was supported:

Printing sheets poster size, A2 up to A0 and putting them on a wall for collaborative marking of points of interest with markers or arrow icons or something.

We were hoping to do that and planning on doing it with FP but found out FP only supports up to A3, just a bit too small for what we hoped to try.

Not sure how hard it would be to support, but if possible, it might make some interesting uses more available.

**Comment by sethfitz** [comment]
Totally. Switching to new printing infrastructure (necessary for handling rotation + branding) makes this dramatically more possible.

**Comment by bgirardot** [comment]
Oh cool. Glad to hear that. I am looking forward to it. I will close this since I know it is on your radar already then. Thank you so much. We love Field Papers!
