### ISSUE TITLE
Rethink survey forms

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#53]
Support more data formats:

Importing OpenDataKit.org forms (XML format)?
---- There is a OpenDataKit Android app, too.
Already kinda support Google Forms import

Partner with ODK on making prints that the Androids can use in the field, and store data back to common table.

Leverage open APIs (Aggregate) to do this?

**Comment by sethfitz** [comment]
Potentially happening in conjunction with [OpenMapKit](https://github.com/AmericanRedCross/OpenMapKit).
