### ISSUE TITLE
Deal with MBTiles in first stage of Make flow

### ISSUE THREAD

**Issue by george08** [stamen/fieldpapers#85]
Display an upload UI under Location search box. Design for success/fail of upload. Store uploaded stuff per user. 

* Should we require login?
* File size limit?

If you've already loaded a tileset, you can use that on Make Step 1 to set your location. Would be good to extract/store/display location embedded in a tileset, so we can display a tileset's location as the information you can use to choose from.

**Comment by sethfitz** [comment]
N/a.
