### ISSUE TITLE
Remove overlap from page extent bbox

### ISSUE THREAD

**Issue by nvkelso** [stamen/fieldpapers#88]
We don't want overlapping page footprints on in page grids like this:
http://fieldpapers.org/print.php?id=ltggf748

In the database, for the metadata return used to build page grids client side.

Alternate solution:

Or provide the offset gutter WITH page orientation.

Right now each page bbox INCLUDES the binding gutter / QR code gutter. Either specify the width of the gutter and page orientation so that can be decomposed client side, or preferably just put the effective BBOX values in instead of the bigger one. Continue to store the bigger one if you want, but use a new different attribute name.

**Comment by sethfitz** [comment]
This applies to an old version of Field Papers. If this still applies, please [open a new issue against the new site](https://github.com/fieldpapers/fieldpapers/issues/new).

See also https://github.com/fieldpapers/fieldpapers/issues/100
